### ISSUE TITLE
Sugestões de melhorias e organização trabalho DCD/SIGES

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/novas-ideias#20]
@Andrelamor, @augustacora, @YanVieira1905 resolvi registrar aqui algumas ideias gerais sobre a estruturação de nosso trabalho utilizando o GitHub:

- **Nome da organização GitHub**: Atualmente lab-mg, mas com sugestão de mudança devido a nova proposta de estrutura tomada pela DCD/SIGES. A princípio não gosto da ideia de mudarmos para automatiza (ou suas variações) pois entendo que o trabalho da diretoria vai além do projeto Automatiza-MG. **Pensando que no futuro os trabalhos tendem a se convergir proponho manter o nome lab-mg**. Não gosto muito da ideia de colocar dcd ou dcd-siges ou até mesmo desburocratizacao (ou suas variações) pois estas siglas/nomes mudam com muita frequência. Outro ponto a favor do nome é a possibilidade de abrirmos a utilização da organização para a equipe atual do Lab, principalmente após a realização [desta apresentação sobre GitHub](https://lab-mg.github.io/reveal.js/presentations/20231218_github/index.html) e os frutos que serão colhidos com nossa gestão do conhecimento.
- **Nome deste repositório**: Tinha pensado em criar um repositório para registro de questões e ou novas ideias, evitando assim a criação de issues em repositórios com assuntos "errados" só pela inexistência de um repositório melhor. Não sei se o nome ou até mesmo o conceito é o melhor. @Andrelamor é um pouco aquela ideia do issue dos issues que tínhamos na dta (que não funcionou muito bem).
- **Campo projeto dos boards planner (GitHub)**: Atualmente temos [5 opções cadastradas](https://github.com/orgs/lab-mg/projects/1/settings/fields/58774318) no campo `projeto` de nosso planner. Penso que deveríamos revisar este cadastro:
     - Agentes de simplificação: serão de nossa responsabilidade?
     - Automatizações - Treinamentos: revisar para Automatiza-MG.
     - Imersão SCAP: Projetos iguais a esses aparecerão a todo momento. Como serão chamados? Particularmente não gosto muito de imersão. Podemos criar um projeto para abarcar todos eles? Precisamos, necessariamente, de um para cada?
     - Mapa de transformação: será de nossa responsabilidade? Acredito que sim.
     - Rotina: sugiro manter para incluir coisas como atas de reuniões e afins.
- **Campo status dos boards planner (GitHub)**: Gosto de poucos status, conforme se encontra atualmente, mas aberto a sugestões. Podemos/devemos adaptar pensando na estrutura do projeto estratégico Automatiza-MG.
- **Campo prioridade dos boards planner (GitHub)**: Gosto de poucas opções, conforme se encontra atualmente, mas aberto a sugestões.
- **Proposta de agenda semanal**:
    - Baseado na ideia de [maker's schedule x manager's schedule](https://www.paulgraham.com/makersschedule.html) sugiro reuniões apenas na parte da manhã. A parte da manhã é menor, o que dificulta a execução de trabalhos que exigem raciocínio (programar, criar robôs, escrever). Sendo perfeita, na minha opinião, para reuniões de alinhamento e/ou até mesmo planejamento de rotinas.
    - Realização de Webinars semanais para, sobre tudo, disseminar conhecimento. A ideia é criar um cronograma de, no máximo, duas horas semanais para discutir assuntos interessantes como artigos (liderança, tecnologia, motivação, organização, etc.), ensinar tópicos novos, praticar a utilização de ferramentas de controle de versão e/ou até praticar programação. A agenda de cada semana ficaria sob a responsabilidade de um integrante da equipe, evitando assim sobrecarga de todos.
- Organização do nosso repositório [handbook](https://lab-mg.github.io/handbook/):
    - Incluir atas de reunião. [O modelo utilizado atualmente](https://lab-mg.github.io/handbook/atas/) não me agrada. Acredito que poderíamos pensar na própria estrutura de blog, que também nos permite a inclusão de [tags](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/?h=blog#adding-tags), facilitando, posteriormente, a identificação destas atas.
    - Centralizar o registro geral de todos os projetos na aba [Linha do tempo](https://lab-mg.github.io/handbook/linha_do_tempo/), facilitando assim a apresentação dos projetos para chefias.
    - Disseminar e utilizar [Guia de estilo](https://lab-mg.github.io/automatizacoes/blog/guia-de-estilo-de-nossas-p%C3%A1ginas/), que, na minha opinião, deveria ficar no handbook e não como post da página Automatiza-MG.

**Comment by Andrelamor** [comment]
> * **Proposta de agenda semanal**:
>   
>   * Baseado na ideia de [maker's schedule x manager's schedule](https://www.paulgraham.com/makersschedule.html) sugiro reuniões apenas na parte da manhã. A parte da manhã é menor, o que dificulta a execução de trabalhos que exigem raciocínio (programar, criar robôs, escrever). Sendo perfeita, na minha opinião, para reuniões de alinhamento e/ou até mesmo planejamento de rotinas.

@gabrielbdornas recortei partes do argumento do autor, que é um pouco redundante e 'puxa a sardinha' 'além da conta' pro lado do programador, na minha humilde opinião; afinal, todos somos administradores e precisamos de _speculative meetings_

> Most powerful people are on the manager's schedule. It's the schedule of command. But there's another way of using time that's common among people who make things, like programmers and writers. They generally prefer to use time in units of half a day at least. You can't write or program well in units of an hour. That's barely enough time to get started.

> (...)

> For someone on the maker's schedule, having a meeting is like throwing an exception. It doesn't merely cause you to switch from one task to another; it changes the mode in which you work.

 acredito que os métodos que vc cita acima (sintetizando em (i) registros e encaminhamentos aqui nos repos, de forma coerente, previsível e organizada + (ii) o método agile adaptado, com plannings e dailys curtas e objetivas) vai amenizar boa parte dessas angústias e interrupções abruptas na agenda. Só repare que o autor do post _maker X manager_ destaca as reuniões na parte da tarde:

> Several times a week I set aside a chunk of time to meet founders we've funded. These chunks of time are at the end of my working day, and I wrote a signup program that ensures all the appointments within a given set of office hours are clustered at the end. Because they come at the end of my day these meetings are never an interruption. (Unless their working day ends at the same time as mine, the meeting presumably interrupts theirs, but since they made the appointment it must be worth it to them.)

 ele justifica pela ausência de interrupções, eu creio que faz isso pq dorme de 3a.m. até 11a.m., ao programar de noite para o trabalho. No nosso caso concreto, eu vou ter uma restrição particular

**Comment by gabrielbdornas** [comment]
> ele justifica pela ausência de interrupções, eu creio que faz isso pq dorme de 3a.m. até 11a.m., ao programar de noite para o trabalho. No nosso caso concreto, eu vou ter uma restrição particular exatamente nas manhãs, às terças e quintas (o que não me impedirá de fazermos as _plannings_ e _reviewes_ na segunda e na sexta pela manhã, se for este o combinado com @YanVieira1905). Particularmente, eu gosto da ideia da primeira _planning_ semanal ser na parte da tarde às segundas-feiras, porque dá tempo de resolver pendências e se reorganizar no primeiro turno do dia/semana.

@Andrelamor, gostei e acho que todas as observações são pertinentes. Acredito que o pior é a imprevisibilidade e a mudança constante. Pois isso exige olhar o tempo todo para e-mail, agenda e Whatsapp, tirando atenção para foco em tarefas importantes. Ficando definido os horários para nosso planejamento/acompanhamento acredito que tudo se resolverá.

**Comment by gabrielbdornas** [comment]
Definições:

- [ ] Mudar o nome para automatiza-mg.

**Comment by Andrelamor** [comment]
> * [x]  Mudar o nome para automatiza-mg.
@gabrielbdornas atualizei o nome da org no link do site estático no **About** em 
![image](https://github.com/automatiza-mg/novas-ideias/assets/52294411/a31f7730-f01f-4669-907a-1325df71f76f)

**Comment by gabrielbdornas** [comment]
@YanVieira1905 e @augustacora, algumas ações realizadas hoje (17/01/2024) com vistas a organizar melhor nosso planner:

- Limpeza dos projetos:


![Image](https://github.com/automatiza-mg/novas-ideias/assets/49699290/82c9d09b-253b-4e83-bd9e-a7495ad7080f)


- Mudança do campo "Duo Date" para "Closet at".
  - Em teoria o "Duo Date" de um Issue é a data final da Iteração, por isso não achei necessário incluir mais este campo no planner.

Também passei um pente fino em alguns Issues para garantir algumas regras que estão apenas na minha cabeça, mas penso em fazer um post sobre, tais como:
  - Issues em Backlog não pode ter o campo Iteração lançado, pois isso indicaria que já o priorizamos e, portanto, ele deveria estar de TO-DO para baixo.
  - Todos os Issues não fechados devem estar na Iteração corrente, com exceção dos itens de Backlog.
  - Todos os Issues devem ter o campo prioridade preenchidos. Facilitando assim a escolha do trabalho ao longo do caminho.

**Comment by Andrelamor** [comment]
@gabrielbdornas diante das últimas tratativas, este issue já poderia ser fechado, não? 

e como não fui citado abaixo, estou desobrigado de seguir essas novas regras, certo? 😁

> [@YanVieira1905](https://github.com/YanVieira1905) e [@augustacora](https://github.com/augustacora), algumas ações realizadas hoje (17/01/2024) com vistas a organizar melhor nosso planner:
> 
> * Mudança do campo "Duo Date" para "Closet at".
>   
>   * Em teoria o "Duo Date" de um Issue é a data final da Iteração, por isso não achei necessário incluir mais este campo no planner.
> 
> Também passei um pente fino em alguns Issues para garantir algumas regras que estão apenas na minha cabeça, mas penso em fazer um post sobre, tais como:
> 
> * Issues em Backlog não pode ter o campo Iteração lançado, pois isso indicaria que já o priorizamos e, portanto, ele deveria estar de TO-DO para baixo.
> * Todos os Issues não fechados devem estar na Iteração corrente, com exceção dos itens de Backlog.
> * Todos os Issues devem ter o campo prioridade preenchidos. Facilitando assim a escolha do trabalho ao longo do caminho.

**Comment by gabrielbdornas** [comment]
@Andrelamor, podemos fechar sim!
